# CREATED BY Bruno 
services:
#  _____                       ______            
# |  __ \                     |  ____|           
# | |__) | __ _____  ___   _  | |__   _ ____   __
# |  ___/ '__/ _ \ \/ / | | | |  __| | '_ \ \ / /
# | |   | | | (_) >  <| |_| | | |____| | | \ V / 
# |_|   |_|  \___/_/\_\\__, | |______|_| |_|\_(_)
#                       __/ |                    
#                      |___/                     

# Proxy
  proxy:
    image: "jwilder/nginx-proxy"
    container_name: "Proxy"
    restart: "always"
    volumes:
      - "prx_certs:/etc/nginx/certs"
      - "prx_vhost:/etc/nginx/vhost.d"
      - "prx_html:/usr/share/nginx/html"
      - "prx_config:/etc/nginx/"
      - "/run/docker.sock:/tmp/docker.sock:ro"
    networks: ["sys_net", "web_net"]
    ports:
      - "443:443"
      - "80:80"

# Letsencrypt
  letsencrypt:
    image: "jrcs/letsencrypt-nginx-proxy-companion"
    container_name: "LetsEncrypt"
    restart: "always"
    depends_on:
      proxy:
        condition: "service_started"
    volumes:
      - "prx_certs:/etc/nginx/certs"
      - "prx_vhost:/etc/nginx/vhost.d"
      - "prx_html:/usr/share/nginx/html"
      - "/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - "NGINX_PROXY_CONTAINER=Proxy"
    networks: ["sys_net"]

#  _    _ _   _ _ _ _         
# | |  | | | (_) (_) |        
# | |  | | |_ _| |_| |_ _   _ 
# | |  | | __| | | | __| | | |
# | |__| | |_| | | | |_| |_| |
#  \____/ \__|_|_|_|\__|\__, |
#                        __/ |
#                       |___/ 

# <-- PLACEHOLDER -->

#  _    _      _                                  
# | |  | |    | |                                 
# | |  | | ___| |__  ___  ___ _ ____   _____ _ __ 
# | |/\| |/ _ \ '_ \/ __|/ _ \ '__\ \ / / _ \ '__|
# \  /\  /  __/ |_) \__ \  __/ |   \ V /  __/ |   
#  \/  \/ \___|_.__/|___/\___|_|    \_/ \___|_|   

# Cyberbear Lab - lab.cyberbear.me
  cyberbearlab:
    image: "php:8.2-apache"
    container_name: "CyberbearLab"
    restart: "always"
    environment:
      - "VIRUTAL_HOST=$VH_CYBERBEAR_LAB"
    volumes:
      - "cbl_webroot:/var/www/"
    networks: ["web_net"]

# Cyberbear Lab - lab.cyberbear.me
  aszscholz:
    image: "php:8.2-apache"
    container_name: "ASZ-Scholz"
    restart: "always"
    environment:
      - "VIRUTAL_HOST=$VH_AUTOHAUS"
    volumes:
      - "asz_webroot:/var/www/"
    networks: ["web_net"]


#  _   _      _                      _        
# | \ | |    | |                    | |       
# |  \| | ___| |___      _____  _ __| | _____ 
# | . ` |/ _ \ __\ \ /\ / / _ \| '__| |/ / __|
# | |\  |  __/ |_ \ V  V / (_) | |  |   <\__ \
# |_| \_|\___|\__| \_/\_/ \___/|_|  |_|\_\___/

networks: # 172.21.0.0/16
# System
  sys_net: # 172.21.1.0/24
    name: "sys_net"
    driver: "bridge"
    ipam:
      config:
        - subnet: "172.21.1.0/24"
          ip_range: "172.21.1.0/24"
          gateway: "172.21.1.1"
# Utility Net
  utl_net: # 172.21.2.0/24
    name: "utl_net"
    driver: "bridge"
    ipam:
      config:
        - subnet: "172.21.2.0/24"
          ip_range: "172.21.2.0/24"
          gateway: "172.21.2.1"
# Webserver Net
  web_net: # 172.21.3.0/24
    name: "web_net"
    driver: "bridge"
    ipam:
      config:
        - subnet: "172.21.3.0/24"
          ip_range: "172.21.3.0/24"
          gateway: "172.21.3.1"
  
# __      __   _                           
# \ \    / /  | |                          
#  \ \  / /__ | |_   _ _ __ ___   ___  ___ 
#   \ \/ / _ \| | | | | '_ ` _ \ / _ \/ __|
#    \  / (_) | | |_| | | | | | |  __/\__ \
#     \/ \___/|_|\__,_|_| |_| |_|\___||___/

volumes:
  prx_certs: # CERTIFIKATE Proxy / Letsencrypt
    name: "prx_certs"
  prx_vhost: # VHOST Proxy / Letsencrypt
    name: "prx_vhost"
  prx_html: # HTML Proxy / Letsencrypt
    name: "prx_html"
  prx_config: # Configuration Proxy
    name: "prx_config"

  cbl_webroot: # Cyberbear Lab
    name: "cbl_webroot"
  asz_webroot: # ASZ Webroot
    name: "asz_webroot"

# CREATED BY Bruno