# CREATED BY Bruno 
services:
#  _____                       ______            
# |  __ \                     |  ____|           
# | |__) | __ _____  ___   _  | |__   _ ____   __
# |  ___/ '__/ _ \ \/ / | | | |  __| | '_ \ \ / /
# | |   | | | (_) >  <| |_| | | |____| | | \ V / 
# |_|   |_|  \___/_/\_\\__, | |______|_| |_|\_(_)
#                       __/ |                    
#                      |___/                     

# Proxy
  proxy:
    image: "jwilder/nginx-proxy"
    container_name: "Proxy"
    restart: "always"
    volumes:
      - "prx_certs:/etc/nginx/certs"
      - "prx_vhost:/etc/nginx/vhost.d"
      - "prx_html:/usr/share/nginx/html"
      - "prx_config:/etc/nginx/"
      - "/run/docker.sock:/tmp/docker.sock:ro"
    networks: ["sys_net", "web_net"]
    ports:
      - "443:443"
      - "80:80"

# Letsencrypt
  letsencrypt:
    image: "jrcs/letsencrypt-nginx-proxy-companion"
    container_name: "LetsEncrypt"
    restart: "always"
    depends_on:
      proxy:
        condition: "service_started"
    volumes:
      - "prx_certs:/etc/nginx/certs"
      - "prx_vhost:/etc/nginx/vhost.d"
      - "prx_html:/usr/share/nginx/html"
      - "/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - "NGINX_PROXY_CONTAINER=Proxy"
    networks: ["sys_net"]

#  _    _      _                                  
# | |  | |    | |                                 
# | |  | | ___| |__  ___  ___ _ ____   _____ _ __ 
# | |/\| |/ _ \ '_ \/ __|/ _ \ '__\ \ / / _ \ '__|
# \  /\  /  __/ |_) \__ \  __/ |   \ V /  __/ |   
#  \/  \/ \___|_.__/|___/\___|_|    \_/ \___|_|   

# ASZ Scholz - asz-scholz.de
  aszscholz:
    image: "php:8.2-apache"
    container_name: "ASZ-Scholz"
    depends_on:
      proxy:
        condition: "service_started"
      letsencrypt:
        condition: "service_started"
    restart: "always"
    environment:
      - "VIRTUAL_HOST=$VH_AUTOHAUS"
      - "LETSENCRYPT_HOST=$VH_AUTOHAUS"
    volumes:
      - "asz_webroot:/var/www/html/"
    networks: ["web_net"]

# ___  ___      _           _     
# |  \/  |     | |         | |    
# | .  . |_   _| |     __ _| |__  
# | |\/| | | | | |    / _` | '_ \ 
# | |  | | |_| | |___| (_| | |_) |
# \_|  |_/\__, \_____/\__,_|_.__/ 
#          __/ |                  
#         |___/                   

  # FlareVM - Malware Lab
  flarevm:
    image: dockurr/windows
    container_name: "FlareVM"
    environment:
      - "VERSION=11"
      - "DISK_SIZE=80G"
      - "USERNAME=$FVM_USERNAME"
      - "PASSWORD=$FVM_USERPASSWORD"
      - "LANGUAGE=German"
      - "REGION=de-DE"
      - "KEYBOARD=de-DE"
    volumes:
      - "/srv/flarevm_data:/storage" # Volume auf sicheren Speicherort auf dem Server abgelegt
    devices:
      - "/dev/kvm" # Entfernen, falls Hardware-Virtualisierung nicht benötigt wird
      - "/dev/net/tun"  # Zugriff auf TUN-Gerät für VPN oder andere Netzwerkoperationen
    cap_add: [] # Entfernt NET_ADMIN, um Netzwerkkontrolle einzuschränken
    ports:
      - "$FVM_RDP_PORT:3389" # RDP-Port für externe Verbindungen geöffnet
    security_opt:
      - no-new-privileges:true # Verhindert Privilegien-Eskalation
    stop_grace_period: 2m
    networks:
      laboratory:
        ipv4_address: "128.0.0.2" # Statische IP innerhalb des Malware-Lab-Netzwerks

  # Remnux - Malware Lab
  remnux:
    image: "remnux/remnux-distro:focal"
    container_name: "Remnux"
    restart: always
    ports:
      - "21546:22" # Portweiterleitung für SSH von außen
    networks:
      laboratory:
        ipv4_address: "128.0.0.3" # Statische IP innerhalb des Malware-Lab-Netzwerks

#  _   _      _                      _        
# | \ | |    | |                    | |       
# |  \| | ___| |___      _____  _ __| | _____ 
# | . ` |/ _ \ __\ \ /\ / / _ \| '__| |/ / __|
# | |\  |  __/ |_ \ V  V / (_) | |  |   <\__ \
# |_| \_|\___|\__| \_/\_/ \___/|_|  |_|\_\___/

networks: # 172.21.0.0/16
# System
  sys_net: # 172.21.1.0/24
    name: "sys_net"
    driver: "bridge"
    ipam:
      config:
        - subnet: "172.21.1.0/24"
          ip_range: "172.21.1.0/24"
          gateway: "172.21.1.1"
# Webserver Net
  web_net: # 172.21.3.0/24
    name: "web_net"
    driver: "bridge"
    ipam:
      config:
        - subnet: "172.21.3.0/24"
          ip_range: "172.21.3.0/24"
          gateway: "172.21.3.1"

# Mallab Net
 # NETINF
 # 128.0.0.0/28
 # 255.255.255.240 --> 128.0.0.1 to 128.0.0.14
  laboratory:
    driver: macvlan
    driver_opts:
      parent: ens0 # Netzwerkschnittstelle des Hosts
    ipam:
      config:
        - subnet: "128.0.0.0/28"
          gateway: "128.0.0.1"
  
# __      __   _                           
# \ \    / /  | |                          
#  \ \  / /__ | |_   _ _ __ ___   ___  ___ 
#   \ \/ / _ \| | | | | '_ ` _ \ / _ \/ __|
#    \  / (_) | | |_| | | | | | |  __/\__ \
#     \/ \___/|_|\__,_|_| |_| |_|\___||___/

volumes:
  prx_certs: # CERTIFIKATE Proxy / Letsencrypt
    name: "prx_certs"
  prx_vhost: # VHOST Proxy / Letsencrypt
    name: "prx_vhost"
  prx_html: # HTML Proxy / Letsencrypt
    name: "prx_html"
  prx_config: # Configuration Proxy
    name: "prx_config"

  flarevm_data: # FlareVM Data
    name: "flarevm_data"

  asz_webroot: # ASZ Webroot
    name: "asz_webroot"
  webroot_webdocs: # Webdocs Webroot
    name: "webroot_webdocs"

# CREATED BY Bruno
