services:
# ___  ___      _           _     
# |  \/  |     | |         | |    
# | .  . |_   _| |     __ _| |__  
# | |\/| | | | | |    / _` | '_ \ 
# | |  | | |_| | |___| (_| | |_) |
# \_|  |_/\__, \_____/\__,_|_.__/ 
#          __/ |                  
#         |___/                   

  # Windows for Reversing
  winville:
    image: "dockurr/windows"
    container_name: "WinVille"
    environment:
      - "VERSION=$WIN_VERSION"
      - "DISK_SIZE=$WIN_DISK_SIZE"
      - "USERNAME=$WIN_USERNAME"
      - "PASSWORD=$WIN_USERPASSWORD"
      - "LANGUAGE=$WIN_LANGUAGE"
      - "REGION=$WIN_REGION"
      - "KEYBOARD=$WIN_KEYBOARD"
    volumes:
      - "win_storage:/storage" # Volume auf sicheren Speicherort auf dem Server abgelegt
    devices:
      - "/dev/kvm" # Entfernen, falls Hardware-Virtualisierung nicht benötigt wird
      - "/dev/net/tun"  # Zugriff auf TUN-Gerät für VPN oder andere Netzwerkoperationen
    cap_add:
      - "NET_ADMIN" # Entfernt NET_ADMIN, um Netzwerkkontrolle einzuschränken
    #tty: true
    #stdin_open: true
    ports:
      - "8006:8006" # Wird für die ersteinrichtung ebnötigt http://<hostip>:8006
      - "$WIN_RDP_PORT:3389/tcp" # RDP-Port für externe Verbindungen geöffnet (tcp)
      - "$WIN_RDP_PORT:3389/udp" # Port UDP - für ?
    #security_opt:
    #  - no-new-privileges:true # Verhindert Privilegien-Eskalation
    #stop_grace_period: 2m
    networks: ["laboratory"]

#  _   _      _                      _        
# | \ | |    | |                    | |       
# |  \| | ___| |___      _____  _ __| | _____ 
# | . ` |/ _ \ __\ \ /\ / / _ \| '__| |/ / __|
# | |\  |  __/ |_ \ V  V / (_) | |  |   <\__ \
# |_| \_|\___|\__| \_/\_/ \___/|_|  |_|\_\___/

networks:
  win_net: # 128.0.0.1/29 > 128.0.0.1 bis 128.0.0.6
    name: "win_net"
    driver: "bridge"
    ipam:
      config:
        - subnet: "128.0.0.0/29"
          ip_range: "128.0.0.0/29"
          gateway: "128.0.0.1"

# __      __   _                           
# \ \    / /  | |                          
#  \ \  / /__ | |_   _ _ __ ___   ___  ___ 
#   \ \/ / _ \| | | | | '_ ` _ \ / _ \/ __|
#    \  / (_) | | |_| | | | | | |  __/\__ \
#     \/ \___/|_|\__,_|_| |_| |_|\___||___/

volumes:
  flarevm_data: # FlareVM Data
    name: "flarevm_data"